[2022-08-23 23:28:50,840] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.carga_arquivo manual__2022-08-23T23:27:47.479841+00:00 [queued]>
[2022-08-23 23:28:50,849] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: raizen_lab_01.carga_arquivo manual__2022-08-23T23:27:47.479841+00:00 [queued]>
[2022-08-23 23:28:50,850] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 23:28:50,851] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-23 23:28:50,851] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 23:28:50,865] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): carga_arquivo> on 2022-08-23 23:27:47.479841+00:00
[2022-08-23 23:28:50,871] {standard_task_runner.py:52} INFO - Started process 90 to run task
[2022-08-23 23:28:50,874] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'raizen_lab_01', 'carga_arquivo', 'manual__2022-08-23T23:27:47.479841+00:00', '--job-id', '9520', '--raw', '--subdir', 'DAGS_FOLDER/raizen_lab_01.py', '--cfg-path', '/tmp/tmp1332lfze', '--error-file', '/tmp/tmp_82vgxld']
[2022-08-23 23:28:50,876] {standard_task_runner.py:80} INFO - Job 9520: Subtask carga_arquivo
[2022-08-23 23:28:50,983] {task_command.py:371} INFO - Running <TaskInstance: raizen_lab_01.carga_arquivo manual__2022-08-23T23:27:47.479841+00:00 [running]> on host 25dd15f8d678
[2022-08-23 23:28:51,088] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=raizen_lab_01
AIRFLOW_CTX_TASK_ID=carga_arquivo
AIRFLOW_CTX_EXECUTION_DATE=2022-08-23T23:27:47.479841+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-23T23:27:47.479841+00:00
[2022-08-23 23:28:51,911] {python.py:173} INFO - Done. Returned value was: None
[2022-08-23 23:28:51,923] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=raizen_lab_01, task_id=carga_arquivo, execution_date=20220823T232747, start_date=20220823T232850, end_date=20220823T232851
[2022-08-23 23:28:51,971] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-23 23:28:52,017] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
